In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn
from tensorflow import keras
import tensorflow as tf
%matplotlib inline

In [2]:
#常量API
t = tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: id=0, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
#String
s = tf.constant('cafe')
print(tf.strings.length(s))

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
#array
s = tf.constant(['apple', 'bananas', 'orange'])
print(tf.strings.length(s))

tf.Tensor([5 7 6], shape=(3,), dtype=int32)


In [7]:
# 变量
v = tf.Variable([[1,2,3], [2,3,4]])
v.numpy()

array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)

In [8]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 4, 6],
       [4, 6, 8]], dtype=int32)>

In [9]:
v[0,2].assign(5)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 4, 5],
       [4, 6, 8]], dtype=int32)>

### 近似求导

In [6]:
def g(x1, x2):
    return x1*5 + (x2**2)

x1 = tf.Variable(2.0)
x2 = tf.Variable(3.0)
with tf.GradientTape(persistent=True) as tape:
    z = g(x1, x2)
dz_dx1 = tape.gradient(z, x1)
dz_dx2 = tape.gradient(z, x2)
print(dz_dx1.numpy(), dz_dx2.numpy())
del tape

5.0 6.0


In [13]:
def g(x1, x2):
    return x1*5 + (x2**2)

x1 = tf.Variable(2.0)
x2 = tf.Variable(3.0)
with tf.GradientTape(persistent=True) as tape:
    z = g(x1, x2)
dz_dx1 = tape.gradient(z, [x1, x2])
print(dz_dx1)

[<tf.Tensor: id=254, shape=(), dtype=float32, numpy=5.0>, <tf.Tensor: id=259, shape=(), dtype=float32, numpy=6.0>]


### datasetAPI的使用

In [14]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int64>
